#!/bin/sh

. ./test.cfg

CONFIGURE_CMD="./echo_false configure script has return error.."

../ccdash.py configure "$CONFIGURE_CMD" -U $CDASH_SUBMIT_URL -S $SITE_NAME -T $CDASH_BUILD_STAMP -B $BUILD_NAME -G $CDASH_GROUP -o out/configure_err.xml $*

#-T -vvv
